# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)'

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
      - develop

trigger:
  batch: true
  branches:
    include:
      - develop
      - develop/*
      - feature/*

pool:
  vmImage: 'windows-2022'

steps:
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'
    verbosityRestore: 'Diagnostic'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '/p:SourceLinkCreate=true'
    projects: '**/*.sln'
    packagesToPack: '**/OpenXmlPowerTools.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    #majorVersion: $(Year:yyyy)
    #minorVersion: $(Month:mm)
    #patchVersion: $(DayOfMonth:dd)
    packagesToPack: '**/OpenXmlPowerTools.csproj'
    versioningScheme: 'byBuildNumber'

- task: NuGetAuthenticate@0
  inputs:
    forceReinstallCredentialProvider: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '4fdce796-ce1c-4d57-aee8-3578f5a2381f'

- task: PublishSymbols@2
  inputs:
    SearchPattern: '**/bin/**/*.pdb'
    SymbolServerType: 'TeamServices'
    IndexableFileFormats: 'Pdb'